### PR TITLE
ENH: add config copy to logging

### PR DESCRIPTION
**Pull request by dengemann**
cc @cmoutard @kingjr @banilo

### CODE REVIEW

**Comment by dengemann** [comment]
Tests pass locally. Could someone please give it a try?

**Comment by cmoutard** [comment]
Works like a charm ! ThX

**Comment by dengemann** [comment]
Thanks for the testing!

2015-04-29 15:39 GMT+02:00 cmoutard notifications@github.com:

**Comment by banilo** [comment]
:+1:

**Pull request merged**
